#!/system/bin/sh

# set VSYNC off
mount -t debugfs debugfs /sys/kernel/debug
echo 0 >/sys/kernel/debug/msm_fb/0/vsync_enable
echo 0 >/sys/kernel/debug/msm_fb/0/hw_vsync_mode
echo 4 >/sys/kernel/debug/msm_fb/0/backbuff
